### ISSUE TITLE
GUI Feature

### ISSUE THREAD

**Issue by CluelessPhil** [Necr0/ConvenientFoundation#1]
So this GUI feature what can a Modpack maker do with it?

**Comment by QbDesu** [comment]
I guess you mean the widget system? Unfortunately, the code systems added are only really usable and relevant for modders. It allows modders to code GUIs more easily. It's not like a build your own GUI feature even though I can see that something like that would be appealing to modpack makers, sorry. At the moment the mod shouldn't really be used at all, unless you really want the slime harvesting and geodes.
